ctl00_MainContent_txtRegistrationDate
ctl00_MainContent_ddlDistrict

ctl00_MainContent_rbMale ctl00_MainContent_rbFemale
ctl00_MainContent_ddlAgeGroup
ctl00_MainContent_ddlEthnicity   ctl00_MainContent_ddlCaste

ctl00_MainContent_rbDiscriminated ctl00_MainContent_rbNotDiscriminated

ctl00_MainContent_txtVisitorPhone ctl00_MainContent_txtFamilyMemberPhone

ctl00_MainContent_ddlVDC ctl00_MainContent_txtWard ctl00_MainContent_txtAddress ctl00_MainContent_chkSameAsPermanent


ctl00_MainContent_ddlEducationalStatus
ctl00_MainContent_ddlMaritalStatus
ctl00_MainContent_ddlNoOfChildren
ctl00_MainContent_ddlNoOfAdultMale
ctl00_MainContent_ddlNoOfAdultFemale
ctl00_MainContent_ddlOccupationType


////Foreign Employment Status
ctl00_MainContent_ddlDecisionStatus
ctl00_MainContent_ddlPassportStatus

ctl00_MainContent_rbJobOfferYes ctl00_MainContent_rbJobOfferNo ctl00_MainContent_ddlJobOfferSource ctl00_MainContent_ddlJobOfferedType
ctl00_MainContent_ddlWorkType
ctl00_MainContent_ddlICKnowledge

ctl00_MainContent_rbMadePaymentYes ctl00_MainContent_rbMadePaymentNo ctl00_MainContent_ddlPaymentRange
ctl00_MainContent_rblPaymentReceiptYes ctl00_MainContent_rblPaymentReceiptNo ctl00_MainContent_ddlPaymentRangeReceipt
ctl00_MainContent_chkNothingYet ctl00_MainContent_ddlPaymentRangeAskedFor


//Optional information
ctl00_MainContent_rbHaveQualificationYes ctl00_MainContent_rbHaveQualificationNo
ctl00_MainContent_rbPrevFEExperienceYes ctl00_MainContent_rbPrevFEExperienceNo
ctl00_MainContent_ddlCountry ctl00_MainContent_ddlVisitFrequency ctl00_MainContent_ddlDestinationAirport

//Services
ctl00_MainContent_txtVisitTimes
ctl00_MainContent_ddlServiceProvided
ctl00_MainContent_rdYes ctl00_MainContent_rbNo ctl00_MainContent_ddlFollowUp

ctl00_MainContent_ddlICRecommendation
ctl00_MainContent_rbAdditionalInfoYes ctl00_MainContent_rbAdditionalInfoNo ctl00_MainContent_cblAdditionalDocument

//Case Documentation
ctl00_MainContent_rbRefferToYes ctl00_MainContent_rbRefferToNo ctl00_MainContent_ddlRefferToYes ctl00_MainContent_ddlRefferToNo
ctl00_MainContent_txtDateofRefferal
ctl00_MainContent_ddlRefferalStatus
ctl00_MainContent_rblDifficultyFaceYes ctl00_MainContent_rblDifficultyFaceNo
ctl00_MainContent_txtDifficultyFaceReason
